### ISSUE TITLE
Callback when transition finishes

### ISSUE THREAD

**Issue by mbrnwsk** [balloob/react-sidebar#103]
Would be great to be able to pass callback when transition finishes on opening/closing sidebar in docked mode, in my case I need to rerender main contet as the layout is broken due delay of transition.

Is there currently any way to solve this?

**Comment by Fallenstedt** [comment]
I've utilized facebook's event emitter system. https://www.npmjs.com/package/fbemitter to create custom events in react applications. You can customize this sidebar by creating an [event that listens to the `sidebarWidth` property. ](https://github.com/balloob/react-sidebar/blob/master/src/sidebar.js#L59)

This event would listen for when the value is `0` or the width that you have specified. When either condition is met, you can trigger an event to rerender your main content.
