### ISSUE TITLE
Latest version of React gives warning for PropTypes

### ISSUE THREAD

**Issue by heather-ea** [balloob/react-sidebar#106]
Is anyone getting this warning in their browser console with the latest version of React?
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by Fallenstedt** [comment]
React.PropTypes is deprecated as of React v15.5. See: https://facebook.github.io/react/docs/typechecking-with-proptypes.html

Sidebar v 2.3.1 uses this npm package now.  I thought updated all references of `React.PropTypes`...Does this warning provide a specific line as to where it is occurring? Is it from the react-sidebar package by any chance?
