### ISSUE TITLE
Sidebar brokes ScrollToTop functional

### ISSUE THREAD

**Issue by indapublic** [balloob/react-sidebar#110]
Sidebar using `overflow: hidden;` on root component and `overflow-y: scroll;` on content component.
ScrollToTop not working with this properties.
I can change these parameters to `initial !important` but open sidebar stay scrollable at this case.

Open sidebar not contain any additional class, isn't it?

**Comment by JesperWe** [comment]
This is just another symptom of the same underlying problem that is described in #77.

**Comment by indapublic** [comment]
Solved by using `BodyClassName` and `{!!this.props.main.sidebarOpen && <BodyClassName className="sidebar-opened" />}`

**Comment by j10sanders** [comment]
Hi @indapublic, can you elaborate on this?  I'm not sure what BodyClassName is referring to
