### ISSUE TITLE
Doesn't close when FastClick is enabled

### ISSUE THREAD

**Issue by Elijen** [balloob/react-sidebar#112]
When `ftlabs/fastclick` is enabled the sidebar will not close even though `open={false}` is passed. It's weird because `onSetOpen` is executed normally.

Might have something to do with how touch events are handled?

**Comment by idanwe** [comment]
@Elijen you can add the class "needsclick" to the overlay with the 
`overlayClassName="needsclick"` option that disable fastclick from interrupt in handling of mobile events
