### ISSUE TITLE
styling the sidebar

### ISSUE THREAD

**Issue by ChrisCreatorArcade** [balloob/react-sidebar#118]
Having trouble styling the sidebar, can anyone give an example?

**Comment by cathal-killeen** [comment]
The styles are passed into the `<Sidebar />` component as the `styles` prop. (Ensure you use `styles` and not `style`, which I personally made the mistake of doing initially.)

The `styles` prop on the sidebar takes an object with 5 keys: `root`, `sidebar`, `content`, `overlay` and `dragHandle`. You can view the default styles on the readme [here](https://github.com/balloob/react-sidebar#styles).

## Inline Styles
The styles are defined as [React Inline Styles](https://react-cn.github.io/react/tips/inline-styles.html). If you are not familiar with inline styles do not be intimidated. Inline styles are essentially JavaScript objects that are compiled to CSS styles on your react components. Inline styles have the same **key/value structure** as CSS styles, however, you must convert the style name to **camelCase**, and wrap the style value in **'quotes'**. For example, the CSS style 
```css
margin-top: 10px;
``` 
is written 
```javascript
marginTop: '10px'
```
with inline styles.

## Example
Say you wanted to add **color** and a **fixed width** to your sidebar. In practice you would define the style object to be passed into the `<Sidebar />` component. Give the object a memorable name and remember to nest the [keys](https://github.com/balloob/react-sidebar#styles) within:
```javascript
const sidebarStyles = {
    sidebar: {
        backgroundColor: 'dodgerblue',
        width: '300px'
    }
}
```
Then when declaring your sidebar instance, pass the style object into the `styles` prop. 

```javascript
<Sidebar styles={sidebarStyles} { ...otherSidebarProps } >
    <b>Main content</b>
</Sidebar>
```

Hopefully this info is useful!

**Comment by vahmur** [comment]
Thanks for this answer - it was userful to me.
Can i change zIndex of opened sidebar by "styles" param or somehow else?
I developing app with complicated html and z-index value 2 is too small for me.
Thank You.

**Comment by vahmur** [comment]
I can change z-index of docked sidebar styles prop. It was a mistake on my side. Thank You.

**Comment by kjr247** [comment]
```
Type error: Type '{ sidebar: { background: string; zIndex: number; }; overlay: { zIndex: number; }; }' is not assignable to type 'SidebarStyles'.
  Types of property 'overlay' are incompatible.
    Type '{ zIndex: number; }' is not assignable to type 'Partial<CSSStyleDeclaration>'.
      Types of property 'zIndex' are incompatible.
        Type 'number' is not assignable to type 'string | null | undefined'.  
```
```
<Sidebar
          sidebar={<ShiftSidebar shift={} onClose={this.handleclose.bind(this)}/>}
          pullRight={true}
          open={this.state.handleopen}
          styles={{
            sidebar: {
              background: 'white',
              zIndex: 6,
            },
            overlay: { zIndex: 5 },
          }}
        > 
```
