### ISSUE TITLE
transitions prop is not working

### ISSUE THREAD

**Issue by bmvinay08** [balloob/react-sidebar#126]
This is how I am using the sidebar:

          <Sidebar sidebar={sidebarContent}
                   open={this.state.sidebarOpen}
                   onSetOpen={this.onSetSidebarOpen}
                   rootClassName={'sidebar-root'}
                   sidebarClassName={'sidebar-main'}
                   contentClassName={'sidebar-content'}
                   overlayClassName={'sidebar-overlay'}
                   pullRight={true}
                   transitions={true}>
            <span></span>
          </Sidebar>
 
I am passing the prop transitions={true} to the Sidebar component, but I am unable to see the slide-in and slide-out effects. Can anyone please tell me what else I need to pass to get this working? Thanks in advance!

**Comment by markusenglund** [comment]
I can't replicate the issue. The `transitions` prop defaults to `true`, so passing it like that is not necessary. I assume you're no longer concerned about this issue after such a long time, so I'm closing. Feel free to reopen it if you think there's something that could be done to fix your problem.
