### ISSUE TITLE
Changing content 'right' default value to hide scrollbar.

### ISSUE THREAD

**Issue by glemiere** [balloob/react-sidebar#145]
Everybody hates these middle-aged browser scroll-bar. Sadly the first thing I noticed when I integrated this component in my app was that a scroll-bar popped on the right.

To fix it on a cross-browser level, we just need to change the 'right' default value of the content, the following way : 

```
  content: {
    right: -15 // this value might need to be even lower in some browsers.
  }
```

Thank you!

**Comment by grsoares21** [comment]
You can just change the style of the content to `overflow: auto` or `overflow: hidden`. The docs tell you how to add different styles for the content or even a custom className to it.

**Comment by glemiere** [comment]
The problem is that `overflow:hidden` is also disabling the scrolling which is not a desired behavior in most cases.

**Comment by grsoares21** [comment]
Ah, I see what you mean. But you'd like to be able to scroll without showing the scroll bar, is that it? 
Either way, I wouldn't change the code for the component, it already allows you to customize the styling. If anything I'd only changge the overflow to auto so it doesn't appear when it's not needed.

**Comment by markusenglund** [comment]
The default style of `overflow` has been changed to `auto` in 3.0 just as @grsoares21 recommended.

**Comment by glemiere** [comment]
Nice, thanks ;)
