### ISSUE TITLE
Make children prop so that it is not required

### ISSUE THREAD

**Issue by bamorgans** [balloob/react-sidebar#148]
I would like to used the sidebar as a standalone component and be able to manage the app content separate.  This is possible right now, but it reports a warning that the prop 'children' is marked as required in the 'Sidebar'.

**Comment by markusenglund** [comment]
This way of using the library is not officially supported by the library right now. As I'm sure you've found out, you have change a lot of the default styling to make it work in a reasonable fashion (removing all the invisible overlays).

In the end the warning goes away in production mode. The warning is still annoying, but it doesn't prevent you from using the library how you like.
