### ISSUE TITLE
The project is no longer maintained. Any alternatives?

### ISSUE THREAD

**Issue by hyzhak** [balloob/react-sidebar#151]
A month ago @balloob wrote https://github.com/balloob/react-sidebar/commit/8b95d3d5b22f58d7893ad85e2dee5b6cc82ca02b#diff-04c6e90faac2675aa89e2176d2eec7d8 that this project is no longer maintained. But is there any recommended alternatives to this component?

**Comment by markusenglund** [comment]
I've taken over maintainership of this library. There are other interesting libraries like `react-burger-menu` and `react-motion-drawer`, but these tend to very big compared to this library in terms of kilobytes. I'll be wading through the open issues and PRs over the coming weeks. Feel free to make an issue or PR of your own you know something that needs fixing!
