### ISSUE TITLE
Scroll main content independently of sidebar

### ISSUE THREAD

**Issue by krisfields** [balloob/react-sidebar#17]
This is an awesome component - thank you for sharing it!

Currently scroll is disabled in the main content area when the sidebar is activated.  Do you know how I can get scroll to work in both the main content area as well as the sidebar at the same time?

**Comment by balloob** [comment]
Setup your element to be scrollable

**Comment by krisfields** [comment]
Could you elaborate?  It looks like the sidebar creates a fixed overlay that is preventing the scrolling of any content underneath, regardless of what overflow is set to.   I'm not great with css though so it's quite possible I'm missing something simple.

**Comment by iam4x** [comment]
@krisfields I agree with you, scrolling fields not smooth at all on iOS :(

**Comment by Ronivan2** [comment]
I was trying to test this out and didn't seemed to work. Tried here on codesandbox: https://codesandbox.io/s/yp638q29rv
it just empty screen.
