### ISSUE TITLE
Fastclick interferes with the sidebar

### ISSUE THREAD

**Issue by salmanm** [balloob/react-sidebar#20]
I have noticed a possible issue with sidebar.

In my mobile app, I have added `menuButtonClick` to all the side menu items to collapse the menu and navigate to a new page. Swipe right/left works perfectly, but clicking on the menu item partially collapses the menu and it gets frozen.

It only happens when fast click is enabled. I think the following might be confusing sidebar.

>Internally, FastClick uses document.createEvent to fire a synthetic click event as soon as touchend is fired by the browser.

As a temporary fix, I am excluding the sidemenu from being `fastclick`ed. But we need to find a more elegant solution for it.

**Comment by balloob** [comment]
This happens because `fastclick` is intercepting events for the sidebar. Excluding it seems like the appropriate fix.
