### ISSUE TITLE
Ability to pass in inline styles to sidebar component

### ISSUE THREAD

**Issue by SYU88** [balloob/react-sidebar#22]
I think this would count as an enhancement, but it'd be great to enable the developer to pass in styles that would be applied to the overlay and the sidebar. I really like how react-modal handles this feature:
https://github.com/rackt/react-modal

Thanks!

**Comment by balloob** [comment]
I agree, that would be a great feature. A PR is welcome :-)

**Comment by SYU88** [comment]
Great! Maybe I'll try taking a crack at it.
