### ISSUE TITLE
How do I use sidebar with a fullwidth top header?

### ISSUE THREAD

**Issue by phun-ky** [balloob/react-sidebar#23]
I'm trying to use this plugin to create the sidebar, but I need a top header aswell for the entire viewport. As it is now, the sidebar dominates the left (or right) side, leaving the attempts to create a fullwidth header div out.

Is there anyway to achieve this?

**Comment by balloob** [comment]
The sidebar is positioned absolute. So just wrap it in a container that keeps space for the header will do.

**Comment by enstulen** [comment]
How would you do that? I can't seem to make it work.

```    
 <Router>
      <Router>
        <div className="App">

          {/* Div wrapped around like this? With 50px space */}
          <div style={{marginTop: 50}}> 
            <Sidebar {...sidebarProps}>
              {menuButton}
              <div style={styles.content}>
                <Main/>
              </div>
            </Sidebar>
          </div>

        </div>
      </Router>
```
