### ISSUE TITLE
Printing Main Content

### ISSUE THREAD

**Issue by czbaker** [balloob/react-sidebar#24]
So, when I go to print content that's in the main area, it's being truncated after on one page with a scrollbar visible.  What's up with that?

![screenshot from 2015-12-10 12-01-10](https://cloud.githubusercontent.com/assets/8585575/11722248/b754ebb0-9f35-11e5-8553-c487233ba979.png)

That's a screenshot of what I'm talking about.  If I were to select the content (images) and do a "print selection", I get two pages of images, as opposed to one page (truncated) and a scrollbar.  Any thoughts?

**Comment by balloob** [comment]
This is a result of how React sidebar is rendering the main content. I don't know a workaround.

**Comment by czbaker** [comment]
That's sort of what I figured.   I don't know a workaround myself, either.  I'll see if I can figure something out later today.

**Comment by aethant** [comment]
@czbaker were you ever able to figure out a workaround? Would a `print`-specific stylesheet help here?

**Comment by czbaker** [comment]
I wasn't able to figure out any sort of workaround.  I think the last I worked on the project that this issue arose in, I was stuck at this point and got frustrated, then holidays happened.

**Comment by balloob** [comment]
You might want to try this. Pass in the following for the styles object for printing:

```json
{
  content: {
    overflow: 'visible'
  }
}
```

**Comment by czbaker** [comment]
I've recently been revisiting a project that was using `react-sidebar`, and this printing issue still persists.  I apologize for basically bringing back a super old thread, but I was wondering if anyone found a workaround.  I tried the above workaround, and it didn't seem to help.

Going to try a print-specific stylesheet.

**Comment by cristian-sima** [comment]
+1

**Comment by cristian-sima** [comment]
@czbaker  Did you solve it ?
