### ISSUE TITLE
Syntax error: Unexpected Token

### ISSUE THREAD

**Issue by ammark47** [balloob/react-sidebar#25]
Hi,
I'm getting this error:
const MaterialTitlePanel = (props) => {
> 17 |   const rootStyle = props.style ? {(error-->...styles.root, error-->...props.style} : styles.root;

I don't think babel 6 supports the spread operator and it might be something we should avoid:
http://stackoverflow.com/questions/31115276/ecmascript-6-spread-operator-in-object-deconstruction-support-in-typescript-and

Any workarounds for the time being?

**Comment by ammark47** [comment]
I used this as work around.
http://stackoverflow.com/questions/33745118/browserify-babel-6-gulp-unexpected-token-on-spread-operator

**Comment by balloob** [comment]
Babel 6 still supports it but it is no longer enabled by default (nothing is).

Possible workarounds:
Use the compiled version in dist-modules (which is the default)
Add this to your `.babelrc`:
```json
{ "plugins": ["transform-object-rest-spread"] }
```
