### ISSUE TITLE
overflow:auto as an option?

### ISSUE THREAD

**Issue by benjeffery** [balloob/react-sidebar#3]
I'd prefer that the scrollbars only appear when there is enough content to overflow. Would it be possible to enable this?

Thanks!

**Comment by balloob** [comment]
Yeah. I'll see if I have some time soon to fix this.

For now, to work around it, add a child that takes 100% height and provides its own scrollbars when needed.

**Comment by benjeffery** [comment]
I can whip up a crude PR if it helps?

**Comment by balloob** [comment]
Sorry, have been really busy. A PR would help. We could probably just hardcode it to be auto?

**Comment by benjeffery** [comment]
Done, I'll close this.
Thanks, really liking react-sidebar!
