### ISSUE TITLE
how to make sidebar background color white for mobile?

### ISSUE THREAD

**Issue by ammark47** [balloob/react-sidebar#30]
Hi, the color is fine for web browsers but when I use it on mobile the sidebar's background becomes transparent. How can I keep it white even in mobile?
![screen shot 2016-01-23 at 8 53 11 pm](https://cloud.githubusercontent.com/assets/12992026/12533981/60ef2ff0-c213-11e5-9d88-1db36f3d3c37.png)

**Comment by balloob** [comment]
Make sure that the component that gets rendered inside the sidebar has a white background.
