### ISSUE TITLE
On scroll event

### ISSUE THREAD

**Issue by mario-jerkovic** [balloob/react-sidebar#31]
There is a problem with the CSS positioning in sidebar. If you want to create an scroll listener the callback function won't be triggered.

**Comment by balloob** [comment]
Correct. I had to cancel the vertical scrolling when you're dragging the sidebar horizontal to prevent user experience.

**Comment by MarioJerkovicDickeys** [comment]
So maybe you can expose callback prop on the sidebar component

**Comment by balloob** [comment]
You should be able to add an event listener on your own component that you mount in the sidebar.

**Comment by MarioJerkovicDickeys** [comment]
Yes, I did that, but at least for me it feels and looks little bit hacky
