### ISSUE TITLE
Relative Positioning &  Custom styles for content - left/right not working

### ISSUE THREAD

**Issue by kert-io** [balloob/react-sidebar#34]
This is sort of two interconnected issues with one underlying cause.

1.  I have a scenario where I need to use relative positioning of the sidebar and contents.  This will work for the most part if I set style as:
```js
           let style = {
			root: {
				position: 'relative',
				display: 'inline-block'
			},
			sidebar: {
				position: 'relative',
				display: 'inline-block',
				'vertical-align': 'top'
			},
			content: {
				position: 'relative',
				display: 'inline-block',
				background: 'white',
			}
		};
```
But the left position is still being overridden by code mentioned in problem two.

2.  Currently doesn't respect if left style is set.  All left positioning is automatically overridden by:
```js
if (this.props.pullRight) {
     contentStyle.right = this.state.sidebarWidth + 'px';
} else {
      contentStyle.left = this.state.sidebarWidth + 'px';
 }
```

The behavior is largely correct for any absolute positioning.  So a simple fix might be just address the case of relative positioning by wrapping the contentStyle code above inside:

```js
if (contentStyle.position !== 'relative') {
    //your existing code 
}
```

**Comment by balloob** [comment]
Using relative positioning and inline-block is causing a very jerky user experience because the browser cannot predict the next change. It can with using absolute positioning and using `left` because it is itself in control of the animation.
