### ISSUE TITLE
Styles are not applied (not overwriting the default ones)

### ISSUE THREAD

**Issue by enrtama** [balloob/react-sidebar#36]
When I create the <Sidebar> object and I send the new styles (as an object), they are not applied.

**Comment by toddgeist** [comment]
I just ran across this issue as well.  However in my case it was because I was passing a "style" prop. whats needed is a "styles" prop. Note the extra "s".  Maybe you did the same thing?

**Comment by MooseSaadat** [comment]
Having the same issue. Some of my styles are applied while others are completely ignored.

**Comment by balloob** [comment]
I can't repro it. Please provide steps to reproduce this issue and re-open.
