### ISSUE TITLE
How to call the sidebar component from the layout component?

### ISSUE THREAD

**Issue by jbenga** [balloob/react-sidebar#37]
Unable to call the sidebar component from the layout component..

**Comment by zeroasterisk** [comment]
demo needed for this, ideally also with `react-router`

**Comment by MimiLau** [comment]
yes demo needed..
but you can also try sth like this
`<button onClick={this.onSetSidebarOpen}>Open</button>`

**Comment by balloob** [comment]
Your own component is responsible for rendering both sidebar and main content. So for a demo have a look at the React state demo: http://facebook.github.io/react/#timerExample
