### ISSUE TITLE
Error: Invariant Violation - React 0.14+

### ISSUE THREAD

**Issue by emilmork** [balloob/react-sidebar#39]
Hi.

After upgrading React and react-sidebar I am getting this error:

```
invariant.js:39 Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of App.jsx
```
Using React 0.14, 0.14.8 and 0.15+

When I was testing the examples in the repo I got another error:
` Cannot set property 'propTypes' of undefined` Using React 0.14 and 0.15.

I have used react-sidebar earlier with react 0.13. 

Is there any known issues with newer versions of React ? I have the latest react-sidebar version.

**Comment by balloob** [comment]
I'm not currently using React Sidebar myself so am not aware of any known issues. If you find the problem, a PR is welcome.

**Comment by emilmork** [comment]
Okey. I may take a look.

**Comment by knikki** [comment]
@emilmork: Any luck with this? I'm getting the same error.

**Comment by emilmork** [comment]
@knikki I did not have the time to look into the issue, so I simply made my own implementation without the fancy animation :)

**Comment by zsherman** [comment]
Looks like @Andrew8xx8 has a fix here https://github.com/Andrew8xx8/react-sidebar/commit/975f772e769ba0e5c68633533032b648bef81f8c.

Mind adding a PR?

**Comment by balloob** [comment]
I can't repro it. Please provide steps to reproduce this issue and re-open.
