### ISSUE TITLE
Cannot get scrollTop position?

### ISSUE THREAD

**Issue by rolz** [balloob/react-sidebar#4]
Hi, 
I need to track the scroll position of the main content but it doesn't work when I use the Sidebar component? Do you know how I can track it?

Best

**Comment by balloob** [comment]
You can add a child as main content that has `height: 100%; overflow: auto;` and so handles the scrolling. Since you own that child you can access the scrollTop.

**Comment by rolz** [comment]
Hey thanks for replying. Can you give and example because I just tried that and doesn't seem to work. 

<Sidebar ref="sidebar" sidebar={sidebarContent}
           open={this.props.openSidebar}
           onSetOpen={this.onSetSidebarOpen}>

           <div className="main">

              <FeedSection />

            </div>

</Sidebar>

CSS:

.main {
  height: 100%;
  overflow: auto;
}

.FeedSection {
  position: relative;
  width: 100%;
  height: 2000px;
  top: 100vh;
  background-color: #fff;
  color: #000;
}


Thanks a lot for your help.

**Comment by rolz** [comment]
Any idea why?

**Comment by clodal** [comment]
It's an issue with the css classes as described in this [StackOverflow answer](https://stackoverflow.com/questions/1174863/javascript-scrollto-method-does-nothing#answer-18573599). A workaround would be to add the following `styles` to the ReactSidebar component:

```
<ReactSidebar
    ...
    styles={{
      root: {
        overflow: 'initial',
      },
      content: {
        overflowY: 'initial',
      },
    }}
>...</ReactSidebar>
```
