### ISSUE TITLE
Scroll on iOS Safari

### ISSUE THREAD

**Issue by adrianha** [balloob/react-sidebar#41]
I feel a bit laggy when i scrolled on Safari (iOS).
Is there any solution to fix this?

**Comment by xdroidx** [comment]
Yes. I found solution here https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/
You just need to overwrite "content" styles like this:
```javascript
class App extends React.Component {
  ...
  sidebarStyles = {
    ...
    content: {overflowY: 'scroll', WebkitOverflowScrolling: 'touch'},
  };
  render() {
    return (
      <Sidebar styles={this.sidebarStyles}>
          {this.props.children}
      </Sidebar>
    );
  }
}
```

And maybe it is a good idea to have such styles by default.

**Comment by SepiaGroup** [comment]
Why is this not the default setting ?

**Comment by Fallenstedt** [comment]
I just implemented these changes and tested it across all browsers and a mobile device.
