### ISSUE TITLE
Compiling the example code

### ISSUE THREAD

**Issue by dvmorris** [balloob/react-sidebar#42]
This is probably a dumb question, but I'm new to this ecosystem. How do you compile the example in your repo? I see that you're using webpack, but I'm not sure what parameters to pass to the command. Thanks in advance for your help!

**Comment by BuddhikaGeasman** [comment]
$npm run dev or
just webpack --watch will transpile the code for you

**Comment by caedmon** [comment]
And for another related  and possibly dumb question, how would you run the example?
