### ISSUE TITLE
Parent container returns warning message

### ISSUE THREAD

**Issue by guilsa** [balloob/react-sidebar#45]
Just like the responsive demo I implemented react-sidebar with MaterialTitlePanel and SidebarContent and could not get it working. I'm running React 15.0.0 and react-sidebar 2.1.2.

warning.js:44Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `MainContainer`.

invariant.js:38Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `MainContainer`.

![image](https://cloud.githubusercontent.com/assets/6107640/15309183/5f0ce9c2-1b99-11e6-8a59-5316a65f390f.png)

**Comment by eisenjulian** [comment]
Seeing the same issue on React v0.14

**Comment by balloob** [comment]
I can't repro it. Please provide steps to reproduce this issue and re-open.

**Comment by robrobkay51** [comment]
has anyone managed to resolve this?
