### ISSUE TITLE
Overlay tap delay

### ISSUE THREAD

**Issue by rvanmil** [balloob/react-sidebar#46]
I noticed the overlay had a tap delay on touch devices. It appears the "react-tap-event-plugin" module is a dependency which automatically fixes this, but I could only figure this out by browsing the source code (the `onTouchTap` event). So I think this module should be a peer dependency?

**Comment by balloob** [comment]
It is up to the person making a project with react-sidebar to include this, but it is not mandatory to run react-sidebar. Making it a peer dependency will give warnings on each install while it is not a necessary piece.

**Comment by rvanmil** [comment]
I see. Perhaps it could be mentioned in the docs then.

**Comment by balloob** [comment]
Yeah, that would be great.

On Sat, May 21, 2016 at 10:32 AM, René <notifications@github.com> wrote:

> I see. Perhaps it could be mentioned in the docs then.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/balloob/react-sidebar/issues/46#issuecomment-220790552>
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.
