### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mql' of undefined

### ISSUE THREAD

**Issue by dvmorris** [balloob/react-sidebar#48]
I am trying the example from the README where the sidebar responds to the browser width, and I get the following error when I resize my browser manually and cross over the threshold of 800px going in either direction:

`Uncaught TypeError: Cannot read property 'mql' of undefined`

Is this the expected behavior?

**Comment by balloob** [comment]
Browser?

**Comment by dvmorris** [comment]
Chrome

**Comment by dvmorris** [comment]
And the error is happening on this line of code:

```javascript
mediaQueryChanged() {
    this.setState({
      sidebarDocked: this.state.mql.matches //triggers error
    });
}
```

**Comment by krijoh92** [comment]
I'm guessing the `this` in the function isn't `this` of the component. Have you tried
`mql.addListener(this.mediaQueryChanged.bind(this))` ?

**Comment by balloob** [comment]
I run Chrome 50 and I do not get this TypeError.

We are using React.createClass so all methods are auto-binded.

**Comment by krijoh92** [comment]
Yeah exactly, I'm guessing @dvmorris is using the `class Component extends React.Componet` syntax

**Comment by balloob** [comment]
Alright, closing this issue then.

Btw bind the method in the constructor, not when attaching it to mql because otherwise you cannot unbind it when component gets unloaded and you get a memory leak.

**Comment by krijoh92** [comment]
Yeah of course @balloob, I didn't think about the unbinding!
