### ISSUE TITLE
Support for alternate CSS? (not absolutely positioned content area)

### ISSUE THREAD

**Issue by zeroasterisk** [balloob/react-sidebar#53]
Is there any way we could not absolutely position the "main page content"?

I run into issues with things like bootstrap media queries and joyride... where the content area is absolutely positioned over to right...  Instead, if we could just make the content area positioned normally and add `padding-left` vs `left` it seems like a more simple solution.

It may be that there are very good reasons why this isn't the case.  But I am running into problems with the current setup.  ideas?

**Comment by balloob** [comment]
When initially building it, I did not find this to be performant enough. However, I'm open for it. So make a prototype and when you proof me wrong I'll be open for a PR to address this.
