### ISSUE TITLE
warning.js:44 Warning: Unkown prop `onTouchTap` on <div> tag. Remove this prop from the element

### ISSUE THREAD

**Issue by cristian-sima** [balloob/react-sidebar#54]
![image](https://cloud.githubusercontent.com/assets/12199042/16692815/27c64730-453b-11e6-8acc-03ab0a0a0cce.png)

**Comment by cristian-sima** [comment]
For the last version of react

**Comment by dijs** [comment]
I am getting this as well. I thought React 15.2.1 would fix it, but it did not.

**Comment by balloob** [comment]
https://github.com/facebook/react/issues/6221

Looks like we need to remove the reference to `onTouchTap` [here](https://github.com/balloob/react-sidebar/blob/master/src/sidebar.js#L320) to make it work with React 15.

I don't have time to do this right now and test that it works so a pull request is welcome.

**Comment by cristian-sima** [comment]
Any idea how can do it? It is really strange to get this error every time

**Comment by zeroasterisk** [comment]
```sh
$ ag onTouchTap node_modules/react-sidebar
node_modules/react-sidebar/dist-modules/sidebar.js
368:          onClick: this.overlayClicked, onTouchTap: this.overlayClicked }),

node_modules/react-sidebar/src/sidebar.js
320:             onClick={this.overlayClicked} onTouchTap={this.overlayClicked} />
```
