### ISSUE TITLE
Accessibility issues 

### ISSUE THREAD

**Issue by cristian-sima** [balloob/react-sidebar#56]
I tested the sidebar using https://github.com/reactjs/react-a11y
and I got these problems

![image](https://cloud.githubusercontent.com/assets/12199042/16774055/168a063e-4863-11e6-8559-c64f1d860a8e.png)

**Comment by balloob** [comment]
Pull request welcome 👍

**Comment by cristian-sima** [comment]
Ok I will give a try today
