### ISSUE TITLE
React v0.15.2+ unknown prop error `onTouchTap`

### ISSUE THREAD

**Issue by agilgur5** [balloob/react-sidebar#60]
I don't even use the `onTouchTap` prop in my code, so it appears to be an invalid passthrough

Stacktrace:
```
warning.js?8a56**:44Warning: Unknown prop `onTouchTap` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Sidebar)
    in div (created by Sidebar)
    in Sidebar (created by MainNavSide)
    in MainNavSide
```

**Comment by balloob** [comment]
Already fixed in latest version https://github.com/balloob/react-sidebar#22

**Comment by agilgur5** [comment]
Ahh it went straight to a PR, that explains why I didn't see any open/closed issues on it, thanks!

**Comment by agilgur5** [comment]
Ahh didn't find any closed issues I searched "unknown prop" because of the spelling error on #54 , thanks!!
