### ISSUE TITLE
Multiple Sidebar

### ISSUE THREAD

**Issue by sajumani** [balloob/react-sidebar#65]
Hi,

How can i have multiple sidebar .. in right and left side

any possibility with this ??

**Comment by lesreaper** [comment]
I'm looking into this as well. SPA. I may try setting up two instances of the component, testing if I can separate their states, and seeing how far that gets me.

**Comment by lesreaper** [comment]
I don't see how this could work with two instances since each instance with a component state would bleed into each other, i.e. "sidebarOpen: true" would open all the instances.

**Comment by sajumani** [comment]
It's done... thanks for support

**Comment by lesreaper** [comment]
Uh, ok. I'd love to hear your solution if you got one.

**Comment by sajumani** [comment]
constructor(props) {
        super(props);
		this.onSetSidebarOpen = open => {
			this.setState({ sidebarOpen: open });
		};
		this.onRightSidebarOpen = open => {
			this.setState({ rightSidebarOpen: open });
		};
		this.toggleSidebar      = this.toggleSidebar.bind(this);
		this.toggleRightSidebar = this.toggleRightSidebar.bind(this);
    }

	toggleSidebar() {
        this.setState({ sidebarOpen: true });
    }
	toggleRightSidebar() {
		this.setState({ rightSidebarOpen: true });
    }

render:

<Sidebar sidebar={sidebarContent} open={this.state.sidebarOpen} onSetOpen={this.onSetSidebarOpen}>
				<Sidebar sidebar={rightSidebarContent} open={this.state.rightSidebarOpen}  onSetOpen={this.onRightSidebarOpen} pullRight ={true}>
				<div className="fullHeight contentContainer">
					{navBar}
					{this.props.children}
					
				</div>
				</Sidebar>
				</Sidebar>

**Comment by sajumani** [comment]
I used 2 component state and 2 methods and 
called the component nested

**Comment by lesreaper** [comment]
I understand the separate states and methods.

What do you mean you "called the components nested?"

BTW, the author said the module wasn't made for this ([see here](https://github.com/balloob/react-sidebar/issues/51)), so kudos to you for figuring it out.

**Comment by steezeburger** [comment]
Not sure why it's out of the scope for this project. I haven't had time to look into it, but I'd like to fork this (or at least take touch support) and build my own. 

I already have a working slidepanel component that supports multiple sidebars, but I have terrible touch support.

**Comment by steezeburger** [comment]
As I was making some changes I thought of an easier approach:

What if you just faked two sidebars by toggling the `pullRight` prop and then pass in a different component for the `sidebar` prop.
