### ISSUE TITLE
Missing Typings for DT or @types

### ISSUE THREAD

**Issue by tomffee** [balloob/react-sidebar#70]
I am currently using combination of React and Typescript and I was wandering if it is possible to find react-sidebar declarations for typescript. Right now I am forced to use ambient module declaration.

**Comment by deivers** [comment]
I need typings or @types too

**Comment by jeroenvervaeke** [comment]
I'm working on it, I'll keep you guys posted

**Comment by jeroenvervaeke** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13350

**Comment by jeroenvervaeke** [comment]
typings are added to DefinitlyTyped
`npm install --save @types/react-sidebar`
