### ISSUE TITLE
Get rid of this warning

### ISSUE THREAD

**Issue by jdelafon** [balloob/react-sidebar#72]
This warning occurs systematically when my window gets narrow enough to switch from docked mode to overlay mode (following the "responsive" example from this repo). Everytime I saw this in my code it was because I forgot to remove in `componentWillUnmount` a listener that I set up in `componentWillMount`:

```
warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Sidebar component.
```

As far as I understand it, it indicates a kind of memory leak, as many instances of the listener are created. But at least fixing it would make console logs cleaner.

N.B. I did add `this.state.mql.removeListener(this.mediaQueryChanged);` in `componentWillUnmount`.

Am I the only one having this?

**Comment by dsteinbach** [comment]
I had it too and it's because I was removing the wrong event handle from the event listener in removeListener:

Bad code:
```
class MyApp extends React.Component {
  componentWillMount() {
    const mql = window.matchMedia(`(min-width: 800px)`);
    mql.addListener(this.mediaQueryChanged.bind(this));
  }

  componentWillUnmount() {
    this.state.mql.removeListener(this.mediaQueryChanged);
  }
  ...
}
```

Working code:
```
let sidebarEventHandle;

class MyApp extends React.Component {
  componentWillMount() {
    const mql = window.matchMedia(`(min-width: 800px)`);
    sidebarEventHandle = this.mediaQueryChanged.bind(this);
    mql.addListener(sidebarEventHandle);
  }

  componentWillUnmount() {
    this.state.mql.removeListener(sidebarEventHandle);
  }
  ...
}
```

**Comment by jdelafon** [comment]
That seems to be it! Thanks
