### ISSUE TITLE
Fixed header issue.

### ISSUE THREAD

**Issue by Extra-lightwill** [balloob/react-sidebar#79]
Is it possible to have a fixed header with this sidebar?

I'm using the menu as a push menu (docked property) and when I make my header fixed the docked property pushes the header elements slightly off-screen? 

I'm wondering whether there is a simple solution to this that I'm missing?

**Comment by balloob** [comment]
Add the header to your content, content position relative, header position absolute.

**Comment by Extra-lightwill** [comment]
Maybe, I didn't explain myself properly: I want to have the header over the main content fixed - I don't understand how that can be achieved without using the 'position: fixed' property.. am I missing something?

**Comment by Extra-lightwill** [comment]
@balloob I tried as you suggested and still the same issue of the header moving off-screen
