### ISSUE TITLE
Architecture Proposal: Avoid rendering all app content in a nested scrolling container (+temp. fix)

### ISSUE THREAD

**Issue by MilllerTime** [balloob/react-sidebar#86]
Love the highly interactive sidebar/drawer! Thanks for this component.

There is however one issue that made this component difficult to adopt in my current project, and causes a handful of accessibility issues (some of which have been called out in other issues). I'll cover these first, then move onto the proposal.

### Current Issues
The `<Sidebar>` component wants to wrap the entire app in some `absolute` positioned `<div>`s and completely removes document-level scrolling. Scrolling is instead moved to a child `<div>`. I've compiled a few disadvantages of this approach:
- Users are basically forced to wrap the top-level of their app in `<Sidebar>`. Placing the sidebar deeper in an app's hierarchy can cause some weird issues if you don't fully understand what's going on under the hood. However it may be desirable to add the sidebar for specific route layouts, which ideally would be simple to do.
- The top-level document no longer scrolls, which:
  - Prevents scroll position from being carried across page refreshes.
  - Disables momentum scrolling on iOS (can be fixed with CSS, but totally not ideal).
  - Disables scroll event dispatch from the `window` object (see #77), which:
    - Breaks common logic used to make headers and other elements "sticky" while scrolling.
    - Breaks simple utilities to scroll elements into view that operate by scrolling the whole document.
    - Other issues with global scroll handling code
  - Prevents printing entire pages, since content is masked inside a viewport-sized `<div>` (see #24).
  - In the same vein as printing, there are some Android devices that allow capturing "long screenshots", where the user starts capturing a screenshot and then can scroll the current page to fit extra content in a single image. I haven't tested this, but wouldn't be surprised if it doesn't work as well.

These issues all stem from structure/layout of this component, which goes against the grain of how web pages typically work.

### Proposal
An interactive sidebar/drawer can be built without wrapping any app content by just using `position: fixed` tricks on all elements (sidebar, drag handle, overlay). The app content is left in the top-level document where is can be scrolled, printed, etc. This works great when all you want is an app drawer for small screens.

Docking the sidebar on large screens presents another challenge though, as the main app content should be pushed aside. This is where wrapping the app in a `div` comes in handy, but I still don't think we need to use absolute positioning and force nested scrolling! That's the root of the problems. Instead, let the wrapper div expand to the full size of the content, keeping scrolling at the document level. When docked, the container can just be pushed/resized horizontally, making room for the sidebar.

One new issue that is introduced from allowing the document to scroll is that it's harder to disable the scrolling. With the sidebar open, swiping up and down or using a scroll wheel will move the document in the background. However, it's very possible to work up a sophisticated hack using hidden overflow on the app content for non-iOS devices, fixed positioning tricks on iOS, and scrollbar width compensation on OSes like Windows that still have space-occupying scrollbars. I've implemented all of these techniques successfully.

Thoughts on this? It may or may not be a breaking change, but I feel it would drastically improve usability and accessibility. If this is seen as viable, I can try to work on a PR.

### Temporary mobile workaround
If all you're after is having a slide-out app drawer on mobile and you are running into these issues, I came up with a workaround using only the `styles` prop that allows you to mount `<Sidebar />` anywhere, and keep your app content external. This does throw a react warning (`children` is a required prop for react-sidebar), but works well.
```JS
// Just showing render() here, obviously you need to track open state, etc.
// I'm assuming `state.isSidebarOpen` is being used to track sidebar state. You can swap this out.
render() {
  const sidebarStyles = {
    root: {
      // Position above overlays or other high z-index elements your app might use
      zIndex: 1000,
      // Detach from right and bottom screen edges as it blocks underlying content
      // This also has the effect of shrinking the component to a width and height of 0
      right: 'auto',
      bottom: 'auto',
      // Allow child sidebar elements to render now that element has collapsed
      overflow: 'visible'
    },
    content: {
      // Detach from right and bottom screen edges as it blocks underlying content (collapses element)
      left: 'auto',
      bottom: 'auto',
      // The dragHandle is inside content element for some reason.
      // Allow it to render now that the parent is collapsed.
      overflow: 'visible'
    },
    sidebar: {
      // Make sidebar fixed, like dragHandle is by default
      position: 'fixed'
    },
    overlay: {
      // Enable/disable overlay interactivity based on open/closed state
      // pointer-events browser support: IE11+
      pointerEvents: this.state.isSidebarOpen ? 'auto' : 'none'
    }
  };

  return (
    <div>
      {/* App content is kept outside of sidebar */}
      <YourApp />

      {/* props only, no children elements! */}
      <Sidebar
        styles={sidebarStyles}
        {...otherSidebarProps}
      />
    </div>
  );
}
```

**Comment by balloob** [comment]
I have no interest in rewriting react-sidebar using the method that you described. If you want that, I suggest you fork this project or create your own.

**Comment by MilllerTime** [comment]
Fair enough.

**Comment by nuclearspike** [comment]
@MilllerTime  Caleb, I'd use a forked version 👍

**Comment by MilllerTime** [comment]
@nuclearspike I'm working on this, however it's a mobile only solution. Does that still interest you?

FWIW, I'm using Yahoo's [react-stickynode](https://github.com/yahoo/react-stickynode) to power a desktop sidebar. In my opinion this combo offers the best UX for each respective platform.

**Comment by jayjaydluffy** [comment]
Hi @MilllerTime. I'm experiencing the same issue as in #77 and would like to use your forked version. However, I'm primarily working on a desktop sidebar and would like to know if your solution addresses desktop as well. Would really appreciate your advice. Thanks.

**Comment by MilllerTime** [comment]
@jayjaydluffy Sorry, but my fork no longer supports desktop at all. However, check out the custom styling I outlined above as a temporary workaround. It positions the entire sidebar as fixed, while allowing the HTML document to stretch out to its natural height, resolving your scrolling issue. It might not work perfectly for you as-is, but I think it's the right direction.

**Comment by glauberramos** [comment]
The position:fixed divs are really bad in my opinion. Right now it breaks my app on desktop version because I can't click on anything on the page.
