### ISSUE TITLE
touch={true} breaks menu on iPhone and iPad

### ISSUE THREAD

**Issue by nazarposhta** [balloob/react-sidebar#87]
I tested my menu on iPhone and iPad (Safari browser) and I found the problem with opened menu - I can't close that by clicking on overlay. And when I change the state to false

> open={this.state.sidebarOpen}

my menu stucks like this

https://monosnap.com/file/05xaCRvsX1uUbFHp6w7dSWntBjwxkr

**Comment by Fallenstedt** [comment]
Hey @nazarposhta I just tested this on my iPad and iPhone 5, 6, and 7 and I cannot reproduce this issue. I am able to close the sidebar by tapping on the overlay. Do you have a code example that I could look at?
