### ISSUE TITLE
Throwing a warning with react-router

### ISSUE THREAD

**Issue by daniel-nelson** [balloob/react-sidebar#89]
I'm getting the following when attempting to use this with react-router:
`Warning: [react-router] You cannot change <Router routes>; it will be ignored`

I tried wrapping <Router></Router> and also wrapping the components rendered by react-router and got this warning both ways.

**Comment by balloob** [comment]
We do not change anything that is passed in so this is not related to React Sidebar.

**Comment by daniel-nelson** [comment]
@balloob that warning gets thrown only when React Sidebar displays itself, so it does seem to be caused by React Sidebar (i.e. when I drag the cursor in from the left to show the sidebar via its built in swipe-to-display, the warning appears)

**Comment by daniel-nelson** [comment]
Looks like it was caused by pulling the Router block into a component, which I did to gain access to the provider-provided state for setting open.
