### ISSUE TITLE
Sidebar rebuild whole page after choose a menu option

### ISSUE THREAD

**Issue by erickles** [balloob/react-sidebar#90]
Hello guys,

I build a web-app with the react-sidebar component and it is working fine so far. My issue is that, after i choose a option from the sidebar (each one has a <Link> from react-router), the component builds the whole page again (refresh page))with my selected page.

Any ideas of how do deal with it?

**Comment by balloob** [comment]
We are only rendering the [passed in children](https://github.com/balloob/react-sidebar/blob/master/src/sidebar.js#L326). If you change the component, yes, React will render each component again
