### ISSUE TITLE
Fixed header while sidebar is docked

### ISSUE THREAD

**Issue by stanleycyang** [balloob/react-sidebar#91]
How do I keep the sidebar inline with a fixed header while scrolling down?

Initially:

<img width="1276" alt="screen shot 2017-01-24 at 4 07 33 pm" src="https://cloud.githubusercontent.com/assets/3037893/22272496/47831af6-e24f-11e6-90ed-5cc54270af34.png">

On scrolling, breakage:

<img width="1276" alt="screen shot 2017-01-24 at 4 07 45 pm" src="https://cloud.githubusercontent.com/assets/3037893/22272498/49035b16-e24f-11e6-82e4-a8cd9470723c.png">

Is there a built-in way to handle this case yet?

**Comment by balloob** [comment]
There is no built-in way and neither will there be, you are responsible for everything that is rendered inside.
