### ISSUE TITLE
Can't close sidebar by clicking outside of sidebar

### ISSUE THREAD

**Issue by dlombardi** [balloob/react-sidebar#92]
I cannot seem to trigger the sidebar to close after clicking outside of it.  this is a functionality demonstrated in the example in the repo.

This is the sidebar component configuration
```
class CartSideBar extends Component {

  componentWillMount() {
    var mql = window.matchMedia(`(min-width: 800px)`);
    mql.addListener(this.mediaQueryChanged);
    this.setState({mql: mql, sidebarDocked: mql.matches});

  }

  componentDidMount() {
    console.log("PROPS: ", this.props);
    // const { dispatch } = this.props;
    // dispatch( toggleCartSidebar() )
  }

  componentWillUnmount() {
    this.state.mql.removeListener(this.mediaQueryChanged);
  }

  mediaQueryChanged() {
    console.log("media query is mobile")
  }

  render() {

    const sidebarProps = {
      sidebar: <Cart />,
      docked: false,
      open: this.props.sideBarOpen,
      touch: true,
      shadow: true,
      pullRight: true,
      touchHandleWidth: 20,
      dragToggleDistance: 30,
    };

    return (
      <Sidebar {...sidebarProps}>
        {this.props.children}
      </Sidebar>
    );
  }
}
```

these are the children 

```
class App extends Component {
  render () {
    const { main, nav } = this.props;
    return (
      <div>
        <CartSideBar>
          <div>
            {nav}
          </div>
          <div>
            {main}
          </div>
        </CartSideBar>
      </div>
    )
  }
}
```

**Comment by fgiarritiello** [comment]
Having the same issue. @dlombardi have you found a solution for this?

**Comment by jeroenbrouwer** [comment]
I've got the same problem

**Comment by Fallenstedt** [comment]
An overlay is generated by this component when the sidebar is active. If you inspect this overlay, you will see it has a prop called "onClick" whose value is a function: 

`  overlayClicked() {
    if (this.props.open) {
      this.props.onSetOpen(false);
    }
  }
`

You may need to add a prop to `sidebarProps` called `onSetOpen`:

`
    const sidebarProps = {
      onSetOpen: this.onSetOpen.bind(this),
      sidebar: <Cart />,
      docked: false,
      open: this.props.sideBarOpen,
      touch: true,
      shadow: true,
      pullRight: true,
      touchHandleWidth: 20,
      dragToggleDistance: 30,
    };
`

and a function in your CartSideBar class:

`
  onSetOpen(open) {
    this.setState({open: open});
  }`

**Comment by luizbaldi** [comment]
Just passing in to thank @Fallenstedt for this solution, it worked perfectly for me :)

**Comment by windmaomao** [comment]
@Fallenstedt works for me too, this should be published in the documentation.
