### ISSUE TITLE
gestures are not working

### ISSUE THREAD

**Issue by agrcrobles** [balloob/react-sidebar#93]
Hey,

I notice that gestures are not working having `touch` enabled, increased `touchHandleWidth` but no way make it work.
Am I missing something?

http://balloob.github.io/react-sidebar/example/

**Comment by Fallenstedt** [comment]
What is the user agent string that your browser is set to? If it's on mobile, then touch events will be recognized. https://developer.chrome.com/multidevice/user-agent
