### ISSUE TITLE
React sidebar overlays on the initial load

### ISSUE THREAD

**Issue by stanleycyang** [balloob/react-sidebar#95]
![screen shot 2017-02-09 at 8 26 49 pm](https://cloud.githubusercontent.com/assets/3037893/22814217/8bc9ab4e-ef06-11e6-8064-12f18fcc3dd7.png)

In this image, you can see the react-sidebar overlaying over the nested portion.

Code looks like this:

```js
      <Sidemenu>

        <main>
          <Header />

          {/* Add common elements */}
          <div className='header-space'>
            {
              cloneElement(children)
            }
          </div>

          <Footer />
        </main>
      </Sidemenu>
```

Suggestions?

**Comment by stanleycyang** [comment]
![screen shot 2017-02-10 at 9 13 04 am](https://cloud.githubusercontent.com/assets/3037893/22836429/3011f99e-ef71-11e6-99b1-3f41f5622de9.png)

Looking at the code it seems like there is an error in which it makes the `left: 126px` for some reason. I tried overriding it with the `styles: { content: {}}` object to no avail.

**Comment by stanleycyang** [comment]
I provided a width and height to the nested sidebar and it fixed it

**Comment by ihmcjacky** [comment]
I am suffering the same issue, may I know more specifically how it can be tackled?

I provided a width and height to the nested sidebar and it fixed it >> I can't quite get the meaning, please advice, thank you
