### ISSUE TITLE
How to close sidebar after clicking on link

### ISSUE THREAD

**Issue by fgiarritiello** [balloob/react-sidebar#96]
Hi,

I love the sidebar so thanks for the hard work. 
When I'm in responsive mode I would like to close the sidebar after I click on a navlink. Is there a way to achieve this?

thanks

**Comment by Fallenstedt** [comment]
One way to achieve this result is by passing a function that toggles the sidebar as a prop into your component that holds nav links...

```
...
  render() {

    const sidebarContent = <SidebarContent />
    const allRoutes = this.props.allRoutes;

    const sidebarProps = {
      sidebar: sidebarContent,
      styles: sidebarStyles,
      open: this.state.open,
      docked: this.state.docked,
      onSetOpen: this.onSetOpen.bind(this),
    };

    return (
      <Sidebar {...sidebarProps}>
        <YourComponent onClick={this.toggleOpen.bind(this)}/>
        {allRoutes}
      </Sidebar>
    );
  }
...
```

then in the component that receives this function (`<YourComponent />`), you can call upon sidebar to close itself when it's clicked.


```
class YourComponent extends Component {

  constructor(props) {
    super(props);
  }

  render() {

    const menuToggle = (
      <a style={{float: 'right'}} onClick={this.props.onClick} href="#" >
         Navigation Link
      </a>
    );

    return (
      <div>
        {menuToggle}
      </div>
    );
  }

};
```

You can also review [some StackOverflow questions](https://stackoverflow.com/questions/26176519/reactjs-call-parent-method) that cover this topic of calling parent methods from child components:

**Comment by fgiarritiello** [comment]
Thanks @Fallenstedt. That's a good workaround.
