### ISSUE TITLE
Add "react-sidebar-opened" and ""react-sidebar-closed" classes to root container

### ISSUE THREAD

**Issue by sametmax** [balloob/react-sidebar#99]
And also "react-sidebar-docked".

This way it's easier to style the main content with CSS by matching the opened and closed state of the side bar. This wouls be especially handy to hide and show the trigger button with a simple css class. Right now I have to propage the events to the render methods, which is a lot of manual work.

**Comment by Fallenstedt** [comment]
By design, React Sidebar does not keep track of whether it is open or not. This has to be done by the parent component. This allows the parent component to make changes to the sidebar and main content based on the open/docked state, which makes it less opinionated
